spring:
  redis:
    host: 127.0.0.1
    port: 6379
    maxmemory: 128M
  datasource:
    url: jdbc:mysql://accountdb.cxkkymmo0avj.ap-northeast-2.rds.amazonaws.com:3306/accountdb?autoReconnect=true
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: MySQL
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화